[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[override]]
  name = "github.com/VividCortex/gohistogram"
  version = "1.0.0"

[[override]]
  name = "github.com/influxdata/influxdb"
  version = "1.7.1"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "v1.0.0-rc1"

[prune]
  go-tests = true
  unused-packages = true