---
  primary:
    address: ":7000"
  health:
    address: ":7001"
    options:
      - "PayloadsOverZero"
      - "PayloadsOverHundred"
      - "PayloadsOverThousand"
      - "PayloadsOverTenThousand"
    readTimeout: "15s"
    idleTimeout: "15s"
  pprof:
    address: ":7002"
    readTimeout: "15s"
    idleTimeout: "15s"
  metric:
    address: ":7003"
    metricsOptions:
      namespace: "webpa"
      subsystem: "tr1d1um"
    readTimeout: "15s"
    idleTimeout: "15s"
  log:
    file: "stdout"
    level: "INFO"
    json: true

  authHeader: ["YXV0aEhlYWRlcg=="]

  db:
    server: "db:26257"
    username: "roachadmin"
    database: "devices"
    numRetries: 4
    waitTimeMult: 5
    connectTimeout: 1m
    opTimeout: 100ms
