---
primary:
  address: ":7100"
health:
  address: ":7101"
  options:
    - "PayloadsOverZero"
    - "PayloadsOverHundred"
    - "PayloadsOverThousand"
    - "PayloadsOverTenThousand"
  readTimeout: "15s"
  idleTimeout: "15s"
pprof:
  address: ":7102"
  readTimeout: "15s"
  idleTimeout: "15s"
metric:
  address: ":7103"
  metricsOptions:
    namespace: "webpa"
    subsystem: "tr1d1um"
  readTimeout: "15s"
  idleTimeout: "15s"
log:
  file: "stdout"
  level: "INFO"
  json: true

endpoint: "/device-status"
parseQueueSize: 3000
insertQueueSize: 3000
maxParseWorkers: 10000
maxInsertWorkers: 1000
maxBatchSize: 30
maxBatchWaitTime: 10ms
metadataMaxSize: 1000
payloadMaxSize: 1000
insertRetries: 0
pruneRetries: 0
pruneInterval: 0s
retryInterval: 10s
defaultTTL: 1h
db:
  server: "db:26257"
  username: "roachadmin"
  database: "devices"
  numRetries: 4
  waitTimeMult: 5
  connectTimeout: 1m
  opTimeout: 100ms
regexRules:
  - regex: "device-status/.*/online$"
    storePayload: true
    ruleTTL: 50h
    eventType: "state"
  - regex: "device-status/.*/offline$"
    storePayload: true
    ruleTTL: 50h
    eventType: "state"

authHeader: ["YXV0aEhlYWRlcg=="]

webhook:
  caduceusSecret: "super secret"
  registrationInterval: 4m
  url: "http://host.docker.internal:8181/api/v1/device-status"
  timeout: "1m"
  registrationURL: "https://127.0.0.1:6000/hook"
  eventsToWatch: ["device-status.*"]
  acquirerConfig:
    sat:
      client: ""
      secret: ""
      satURL: ""
      timeout: 5m
